sonar.projectKey=OscarRomero1717_PollaBizagi
sonar.organization=oscarromero1717
sonar.projectName=Polla Mundialista

# Fuentes analizadas
sonar.sources=backend/src,frontend/polla-web/src
sonar.tests=backend/tests,frontend/polla-web/src
sonar.test.inclusions=**/*Tests.cs,**/*.spec.ts

# Exclusiones (artefactos, seed demo, config local)
sonar.exclusions=**/node_modules/**,**/dist/**,**/obj/**,**/bin/**,**/Migrations/**,**/SeedData.cs,**/appsettings*.json,**/environment*.ts,**/coverage/**,**/TestResults/**

# Cobertura .NET (xUnit + Coverlet)
sonar.cs.vscoveragexml.reportsPaths=backend/TestResults/**/coverage.cobertura.xml

sonar.sourceEncoding=UTF-8
